CREATE TABLE IF NOT EXISTS EMPLOYEES(
    EMP_ID INT,
    EMP_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2) DEFAULT NULL
);
INSERT OR IGNORE INTO EMPLOYEES VALUES(1,'Alice Johnson','HR',50000.00);
INSERT OR IGNORE INTO EMPLOYEES VALUES(2,'Bob Smith','IT',65000.00);
INSERT OR IGNORE INTO EMPLOYEES VALUES(3,'Charlie Brown','Finance',70000.00);
INSERT OR IGNORE INTO EMPLOYEES VALUES(4,'David Wilson','IT',72000.00);
INSERT OR IGNORE INTO EMPLOYEES VALUES(5,'Ella White','HR',48000.00);
INSERT INTO EMPLOYEES(EMP_ID,EMP_NAME,DEPARTMENT)
 VALUES(7,'Grace Hall','IT');
SELECT *FROM EMPLOYEES;