CREATE TABLE IF NOT EXISTS Employees(
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10,2)
);
INSERT OR IGNORE INTO Employees VALUES(1,'Alice Johnson','HR',50000.00);
INSERT OR IGNORE INTO Employees VALUES(2,'Bob smith','IT',65000.00);
INSERT OR IGNORE INTO Employees VALUES(3,'Charlie Brown','Finance',70000.00);
INSERT OR IGNORE  INTO Employees VALUES(4,'David Wilson','IT',72000.00);
INSERT OR IGNORE  INTO Employees VALUES(5,'Ella White','HR',48000.00);
INSERT INTO Employees VALUES(6,'Frank Green','HR',55000.00);
SELECT EMP_NAME
FROM Employees;

